# Server port configuration
#server:
#  port: 8001

# Spring application configuration
spring:
  application:
    name: user-service

  # config-client
  config:
    import: optional:configserver:http://localhost:8888/

  # Database configuration
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness_user_db
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
    
  # JPA and Hibernate configuration
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format-sql: true
#        use-sql-comments: true

# Eureka client configuration
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${random.value}